# Generated by Django 3.2.9 on 2021-11-24 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import training.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=150)),
                ('istrue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('qc beverage', 'qc beverage'), ('qc packaging', 'qc packaging'), ('qa', 'qa'), ('production beverage', 'production beverage'), ('production packaging', 'production packaging'), ('warehouse beverage', 'warehouse packaging'), ('utility', 'utility'), ('sales', 'sales'), ('GA', 'GA'), ('HR', 'HR')], default='production beverage', max_length=20)),
                ('is_trainer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mandatory', 'mandatory'), ('additional', 'additional')], default='mandatory', max_length=15)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('material', models.FileField(upload_to=training.models.Training_master.upload_path)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pass_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Training_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('eval_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('passed', 'passed'), ('failed', 'failed')], max_length=10, null=True)),
                ('is_retake', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.training_master')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training_master')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.answer')),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.evaluation_master')),
                ('training_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training_instance')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.evaluation_master'),
        ),
    ]
